### ISSUE TITLE
Criar interface para criação de vagas

### ISSUE THREAD

**Issue by luiz-fern4ndo** [lfstos/jobmatch#9]
Tarefa: 
- Criar um formulário para as empresas criarem vagas.

Descrição: 
- A empresa poderá cadastrar a vaga com os campos necessários (nome da vaga, faixa salarial, requisitos, escolaridade mínima).

**Comment by lfstos** [comment]
- Refatorar o model Candidato, mover para dentro de vagas, os testes e etc.
- Verificar porque quando tenta cadastrar uma vaga, o sistema não está conseguindo localizar o template

**Comment by lfstos** [comment]
Verificar o erro do formulário ao rodar os testes.
